const mongoose = require('mongoose');

const inputSchema = new mongoose.Schema({
    neighborhood: {
        type: String,
        enum: ["Astoria",
        "Long Island City",
        "Jackson Heights",
        "Flushing",
        "Forest Hills",
        "Jamaica",
        "Bayside",
        "Elmhurst",
        "Fresh Meadows",
        "Rego Park",
        "Woodside",
        "Howard Beach",
        "Richmond Hill",
        "Queens Village",
        "Rockaway Beach",
        "Whitestone",
        "Sunnyside",
        "Cambria Heights",
        "Ridgewood",
        "Maspeth",
        "Ozone Park",
        "South Ozone Park",
        "Woodhaven",
        "Middle Village",
        "College Point",
        "Bellerose",
        "Douglaston",
        "Little Neck",
        "Springfield Gardens",
        "Glen Oaks",
        "Laurelton",
        "Rosedale",
        "Kew Gardens",
        "Kew Gardens Hills",
        "Hollis",
        "Holliswood",
        "Queensboro Hill",
        "Briarwood",
        "Far Rockaway",
        "Arverne",
        "Edgemere",
        "Belle Harbor",
        "Neponsit",
        "Breezy Point",
        "Broad Channel",
        "Somerville",
        "Steinway",
        "North Corona",
        "South Jamaica",
        "St. Albans",
        "Hunters Point"],
        required: true,
    },
    issue: {
        type: String,
        enum: ["Immigration", "Public Health", "Voting", "Education", "Housing"],
        required: true,
    },
    text: {
        type: String,
        maxLength: 300,
    }
}, {
    timestamps: true,
});

module.exports = mongoose.model('Input', inputSchema);